apiVersion: apps/v1
kind: Deployment
metadata:
  name: adService
  labels:
    app: adService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adService
  template:
    metadata:
      labels:
        app: adService
    spec:
      containers:
        - name: adService
          image: gcr.io/google-samples/microservices-demo/emailservice
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"

---
apiVersion: v1
kind: Service
metadata:
  name: adService
spec:
  type: ClusterIP
  selector:
    app: adService
  ports:
    - name: adService
      port: 9555
      targetPort: 9555
