apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogservice
  labels:
    app: catalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogservice
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
        - name: catalogservice
          image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.4.0
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogservice
spec:
  type: ClusterIP
  selector:
    app: catalogservice
  ports:
    - name: catalogservice
      port: 3550
      targetPort: 3550
