apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutService
  labels:
    app: checkoutService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutService
  template:
    metadata:
      labels:
        app: checkoutService
    spec:
      containers:
        - name: checkoutService
          image: gcr.io/google-samples/microservices-demo/checkoutservice
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "catalogService:3550"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingService:5051"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentService:5051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailService:8080"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyService:7000"
            - name: CART_SERVICE_ADDR
              value: "cartService:7070"

---
apiVersion: v1
kind: Service
metadata:
  name: checkoutService
spec:
  type: ClusterIP
  selector:
    app: checkoutService
  ports:
    - name: checkoutService
      port: 5050
      targetPort: 5050
