apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
  labels:
    app: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendservice
  template:
    metadata:
      labels:
        app: frontendservice
    spec:
      containers:
        - name: frontendservice
          image: gcr.io/google-samples/microservices-demo/frontend:v0.4.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "catalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:5051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "adservice:9555"

---
apiVersion: v1
kind: Service
metadata:
  name: frontendservice
spec:
  type: NodePort
  selector:
    app: frontendservice
  ports:
    - name: frontendservice
      port: 8080
      targetPort: 8080
      nodePort: 8080
