apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx
  labels:
    app: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendService
  template:
    metadata:
      labels:
        app: frontendService
    spec:
      containers:
        - name: frontendService
          image: gcr.io/google-samples/microservices-demo/frontend
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "catalogService:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyService:7000"
            - name: CART_SERVICE_ADDR
              value: "cartService:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendService:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingService:5051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutService:5050"
            - name: AD_SERVICE_ADDR
              value: "adService:9555"

---
apiVersion: v1
kind: Service
metadata:
  name: frontendService
spec:
  type: ClusterIP
  selector:
    app: frontendService
  ports:
    - name: frontendService
      port: 8080
      targetPort: 8080
