apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentService
  labels:
    app: paymentService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentService
  template:
    metadata:
      labels:
        app: paymentService
    spec:
      containers:
        - name: paymentService
          image: gcr.io/google-samples/microservices-demo/paymentservice
          ports:
            - containerPort: 5051
          env:
            - name: PORT
              value: "5051"

---
apiVersion: v1
kind: Service
metadata:
  name: paymentService
spec:
  type: ClusterIP
  selector:
    app: paymentService
  ports:
    - name: paymentService
      port: 5051
      targetPort: 5051
