apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendService
  labels:
    app: recommendService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendService
  template:
    metadata:
      labels:
        app: recommendService
    spec:
      containers:
        - name: recommendService
          image: gcr.io/google-samples/microservices-demo/recommendationservice
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: recommendService
spec:
  type: ClusterIP
  selector:
    app: recommendService
  ports:
    - name: recommendService
      port: 8080
      targetPort: 8080
