apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendservice
  labels:
    app: recommendservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendservice
  template:
    metadata:
      labels:
        app: recommendservice
    spec:
      containers:
        - name: recommendservice
          image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.4.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: recommendservice
spec:
  type: ClusterIP
  selector:
    app: recommendservice
  ports:
    - name: recommendservice
      port: 8080
      targetPort: 8080
