apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisService
  labels:
    app: redisService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisService
  template:
    metadata:
      labels:
        app: redisService
    spec:
      containers:
        - name: redisService
          image: redis:alpine
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redisService
spec:
  type: ClusterIP
  selector:
    app: redisService
  ports:
    - name: redisService
      port: 6379
      targetPort: 6379
